apiVersion: v1
kind: Pod
metadata:
  name: pod-p1q19
  labels:
     exam: ckad
spec:
  containers:
  - name: app1
    image: nginx
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  - name: app2
    image: tomcat
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
