apiVersion: v1
kind: Pod
metadata:
  labels:
    exam: ckad
  name: pod-p2q10
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: ckad-exam
            operator: In
            values:
            - practice
  containers:
  - image: nginx
    name: test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
