apiVersion: v1
kind: Pod
metadata:
  labels:
    exam: ckad
  name: pod-p2q3
spec:
  containers:
  - name: nginx
    image: nginx
    env: 
    - name: DB-HOST-NAME
      valueFrom:
         configMapKeyRef:
           name: config-map-p2q3
           key: my-db-host
    - name: DB-PORT
      valueFrom:
         configMapKeyRef:
           name: config-map-p2q3
           key: db-port
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  