apiVersion: v1
kind: Pod
metadata:
  name: pod-p2q5
spec:
  containers:
  - name: app
    image: tomcat
    resources:
      requests:
        memory: "64Mi"
        cpu: 1
  - name: log-aggregator
    image: nginx
    resources:
      requests:
        memory: 64Mi
        cpu: 2000m
      limits:
        memory: "128Mi"
        cpu: "2000m"
