apiVersion: v1
kind: Pod
metadata:
  labels:
    exam: ckad
  name: pod-p2q6
spec:
  containers:
  - image: nginx
    name: con1
    resources:
      requests:
        memory: "64Mi"
        cpu: "25m"
      limits:
        memory: "128Mi"
        cpu: "25m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
