apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-p2q7
rules:
- apiGroups:
  - ""
  resourceNames:
  - pod-p2q7-1
  resources:
  - pods
  verbs:
  - get
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-p2q7
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-p2q7
subjects:
- kind: ServiceAccount
  name: ckad-service-account
  namespace: default
  
---

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-1
  name: pod-p2q7-1
spec:
  containers:
  - image: nginx
    name: pod-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  
---

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-1
  name: pod-p2q7-2
spec:
  containers:
  - image: nginx
    name: pod-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
