apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-allow--p2q8
  namespace: default
spec:
  podSelector:
    matchLabels:
      run: pod-p2q8-nginx
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              run: pod-p2q8-tomcat
      ports:
        - protocol: TCP
          port: 80
  