apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: role-p3q10
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-p3q10
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-p3q10
subjects:
- kind: ServiceAccount
  name: ckad-service-account
  namespace: default


