apiVersion: v1
kind: Pod
metadata:
  name: pod-p3q3
spec:
  containers:
  - name: app
    image: tomcat
    resources:
      requests:
        memory: "64Mi"
        cpu: 0.5
  - name: log-aggregator
    image: nginx
    resources:
      requests:
        memory: "64Mb"
        cpu: 250m
      limits:
        memory: "128Mi"
        cpu: "500m"