apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-p3q7
  labels:
    exam: ckad
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"
    
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-p3q7
  labels:
    exam: ckad
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
      
---

apiVersion: v1
kind: Pod
metadata:
  name: pv-pod-p3q7
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: pv-claim-p3q7
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage