apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test
  name: test
  namespace: default
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: test
    resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: test
  name: my-service1
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: test
  sessionAffinity: None
  type: ClusterIP
